// <auto-generated>
//   Generated from the 7 Days to Die V3.0 sandbox option table.
//   Source: https://github.com/Labyricorn/7D2D-Sandbox-Settings-Reports
//   Do not edit by hand. See SandboxCodeService for the encoding.
// </auto-generated>
#nullable enable

namespace SevenDaysManager.Models;

/// <summary>One sandbox option: its enum id, the values it accepts, and its default.</summary>
/// <param name="Id">Enum id. Encoded as 2 base-26 letters (0 = "AA", 26 = "BA").</param>
/// <param name="Name">The game's internal name, e.g. "ZombieMove".</param>
/// <param name="Display">Human label, e.g. "Zombie Speed (Day)".</param>
/// <param name="Category">Top-level group, e.g. "Enemies".</param>
/// <param name="Values">Allowed values IN ORDER. The code stores the INDEX into this list
///   as a single letter ('A' = index 0), so order is load-bearing.</param>
/// <param name="Default">The engine default. Options left at their default are omitted
///   from the code entirely — except the six difficulty fields, which are always written.</param>
/// <param name="IsBool">True when the option is a two-state False/True.</param>
/// <param name="IsPercent">True when the value should be shown as a percentage.</param>
public sealed record SandboxOption(
    int Id,
    string Name,
    string Display,
    string Category,
    IReadOnlyList<double> Values,
    double Default,
    bool IsBool,
    bool IsPercent)
{
    /// <summary>Index of <see cref="Default"/> within <see cref="Values"/>; -1 if absent.</summary>
    public int DefaultIndex => IndexOf(Default);

    public int IndexOf(double value)
    {
        for (var i = 0; i < Values.Count; i++)
            if (Math.Abs(Values[i] - value) < 0.0001) return i;
        return -1;
    }
}

public static class SandboxSettings
{
    /// <summary>
    /// The six difficulty fields. These are ALWAYS emitted into the code, even when they sit at
    /// their default — the game's own presets do this (Warrior writes "BND", and D is
    /// AISmellMode's default). Omitting them breaks byte-compatibility with the stock presets.
    /// </summary>
    public static readonly IReadOnlySet<string> AlwaysWritten = new HashSet<string>
    {
        "RangedDamage",
        "MeleeDamage",
        "BlockDamage",
        "TerrainDamage",
        "IncomingDamage",
        "AISmellMode",
    };

    /// <summary>
    /// Every sandbox option, IN THE GAME'S UI ORDER.
    ///
    /// ⚠ The order of this list is load-bearing. The game emits code blocks in UI order, not in
    /// enum-id order — verified by round-tripping the 16 stock preset codes (15 match byte-for-byte;
    /// the 16th, Madmoles Mayhem, is hand-authored out of order and still decodes identically).
    /// Re-ordering this list changes the codes we emit.
    /// </summary>
    public static readonly IReadOnlyList<SandboxOption> All = new SandboxOption[]
    {
        new(  0, "RangedDamage", "Ranged Damage", "General",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new(  1, "MeleeDamage", "Melee Damage", "General",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new(  2, "BlockDamage", "Block Damage", "General",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new(  3, "TerrainDamage", "Terrain Damage", "General",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new(  4, "HeadshotMultiplier", "Headshot Multiplier", "General",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new( 17, "IncomingDamage", "Incoming Damage", "General",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new(  6, "WalkSpeed", "Walk Speed", "General",
            new double[] { 0.25, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2, 3 }, 1, false, false),
        new(  7, "RunSpeed", "Run Speed", "General",
            new double[] { 0, 0.25, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2, 3 }, 1, false, false),
        new(  5, "CrouchSpeed", "Crouch Speed", "General",
            new double[] { 0, 0.25, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2, 3 }, 1, false, false),
        new(  8, "JumpStrength", "Jump Height", "General",
            new double[] { 0, 0.5, 1, 1.25, 1.5, 2, 3 }, 1, false, false),
        new( 10, "StaminaRegen", "Stamina Regen", "General",
            new double[] { 0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3 }, 1, false, false),
        new(  9, "StaminaUsage", "Stamina Usage", "General",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2 }, 1, false, false),
        new( 18, "XPMultiplier", "XP Multiplier", "General",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 3, 5 }, 1, false, false),
        new( 19, "ShowXP", "Show XP", "General",
            new double[] { 0, 1, 2, 3 }, 0, false, false),
        new( 11, "PlayerLevelBonusApplied", "Level Health/Stam Bonus", "General",
            new double[] { 0, 1 }, 1, true, false),
        new(116, "SkillGainRate", "Skill Gain Rate", "General",
            new double[] { 1, 2, 3, 4, 5 }, 1, false, false),
        new(117, "SkillPointsPerLevel", "Skill Gain Amount", "General",
            new double[] { 0, 1, 2, 3, 4, 5, 6, 7 }, 1, false, false),
        new( 26, "DeathPenalty", "Death Penalty", "General",
            new double[] { 0, 1, 2, 3 }, 1, false, false),
        new( 22, "LoseItemsOnDeathType", "Lose Items Death Type", "General",
            new double[] { 0, 1, 2, 3, 4, 5 }, 0, false, false),
        new( 23, "LoseItemsOnDeathCount", "Lose Items Death Count", "General",
            new double[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }, 1, false, false),
        new( 24, "DegradeItemsOnDeath", "Degrade Items On Death", "General",
            new double[] { 0, 1, 2, 3 }, 0, false, false),
        new( 25, "DegradeAmountOnDeath", "Degrade Amount On Death", "General",
            new double[] { 0, 0.05, 0.1, 0.15, 0.2, 0.25 }, 0.1, false, true),
        new( 27, "DropOnDeath", "Drop On Death", "General",
            new double[] { 0, 1, 2, 3, 4 }, 1, false, false),
        new( 28, "DropOnQuit", "Drop On Quit", "General",
            new double[] { 0, 1, 2, 3 }, 0, false, false),
        new( 29, "InfectionRate", "Infection Rate", "General",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3 }, 1, false, true),
        new( 15, "NewbieCoat", "Allow Newbie Coat", "General",
            new double[] { 0, 1 }, 1, true, false),
        new( 20, "EncumbranceModifier", "Encumbrance Modifier", "General",
            new double[] { 10, 1.35, 1, 0.7, 0.35, 0 }, 1, false, false),
        new( 12, "JarRefund", "Jar Refund", "General",
            new double[] { 0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1 }, 0.6, false, true),
        new( 30, "EnemySpawnMode", "Enemy Spawn", "Entities",
            new double[] { 0, 1 }, 1, true, false),
        new( 43, "MaxEnemyTier", "Max Enemy Type", "Entities",
            new double[] { 0, 1, 2, 3, 4, 5 }, 5, false, false),
        new( 46, "BiomeEnemyDensity", "Biome Enemy Density", "Entities",
            new double[] { 0, 1, 2, 3, 4, 5 }, 0, false, false),
        new( 44, "BiomeZombieRespawn", "Biome Enemy Respawn", "Entities",
            new double[] { 0, 1, 2, 3, 4, 5 }, 0, false, false),
        new( 45, "BiomeAnimalRespawn", "Biome Animal Respawn", "Entities",
            new double[] { 0, 1, 2, 3, 4, 5 }, 0, false, false),
        new( 31, "EntityDamage", "Entity Damage", "Entities",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new( 42, "EntityIncomingDamage", "Entity Incoming Damage", "Entities",
            new double[] { 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new( 32, "BlockDamageAI", "Entity Block Damage", "Entities",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new( 33, "BlockDamageAIBM", "Blood Moon Block Damage", "Entities",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new( 16, "HeadshotMode", "Headshot Mode", "Entities",
            new double[] { 0, 1, 2 }, 0, false, false),
        new( 13, "ShowHealthBars", "Entity Health Bars", "Entities",
            new double[] { 0, 1 }, 0, true, false),
        new( 14, "ShowEnemyDamage", "Show Entity Damage", "Entities",
            new double[] { 0, 1 }, 0, true, false),
        new( 34, "ZombieMove", "Zombie Day Speed", "Entities",
            new double[] { 0, 1, 2, 3, 4 }, 0, false, false),
        new( 35, "ZombieMoveNight", "Zombie Night Speed", "Entities",
            new double[] { 0, 1, 2, 3, 4 }, 3, false, false),
        new( 36, "ZombieFeralMove", "Zombie Feral Speed", "Entities",
            new double[] { 0, 1, 2, 3, 4 }, 3, false, false),
        new( 37, "ZombieBMMove", "Zombie Blood Moon Speed", "Entities",
            new double[] { 0, 1, 2, 3, 4 }, 3, false, false),
        new( 38, "ZombieFeralSense", "Zombie Feral Sense", "Entities",
            new double[] { 0, 1, 2, 3 }, 0, false, false),
        new( 39, "AISmellMode", "Zombie AI Smell Mode", "Entities",
            new double[] { 0, 1, 2, 3, 4, 5 }, 3, false, false),
        new( 41, "ZombieRageChance", "Zombie Rage Chance", "Entities",
            new double[] { 0, 0.15, 0.3, 0.35, 0.4, 0.5, 0.6, 0.75, 0.9, 1 }, 0.15, false, false),
        new( 40, "AllowZombieDigging", "Allow Zombie Digging", "Entities",
            new double[] { 0, 1 }, 1, true, false),
        new( 47, "ZombiesEatAnimals", "Zombies Eat Animals", "Entities",
            new double[] { 0, 1 }, 1, true, false),
        new( 60, "GlobalGSModifier", "Global GameStage", "World",
            new double[] { 0.25, 0.5, 1, 1.5, 2 }, 1, false, false),
        new( 61, "BiomeGSModifier", "Biome GameStage", "World",
            new double[] { 0.25, 0.5, 1, 1.5, 2 }, 1, false, false),
        new( 55, "BiomeProgression", "Biome Progression", "World",
            new double[] { 0, 1 }, 1, true, false),
        new( 56, "TemperatureSurvival", "Temperature Survival", "World",
            new double[] { 0, 1 }, 1, true, false),
        new( 74, "MaxTechType", "Max Tech Type", "World",
            new double[] { 0, 1, 2, 3, 4 }, 4, false, false),
        new( 73, "WorkstationsInTheWild", "Workstations in the Wild", "World",
            new double[] { 0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1 }, 0, false, false),
        new( 48, "BloodMoonFrequency", "Blood Moon Frequency", "World",
            new double[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 14, 20, 30 }, 7, false, false),
        new( 49, "BloodMoonRange", "Blood Moon Range", "World",
            new double[] { 0, 1, 2, 3, 4, 7, 10, 14, 20 }, 0, false, false),
        new( 51, "BloodMoonEnemyCount", "Blood Moon Count", "World",
            new double[] { 4, 6, 8, 10, 12, 16, 24, 32, 64 }, 8, false, false),
        new( 50, "BloodMoonWarning", "Blood Moon Warning", "World",
            new double[] { 0, 1, 2 }, 1, false, false),
        new( 52, "AirDropFrequency", "Air Drops", "World",
            new double[] { 0, 1, 2, 3, 4, 5, 6 }, 3, false, false),
        new( 54, "AirDropRandomTime", "Air Drop Random Time", "World",
            new double[] { 0, 1, 2, 3, 4, 5, 6 }, 0, false, false),
        new( 57, "StormFreq", "Storm Frequency", "World",
            new double[] { 0, 0.5, 1, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 58, "StormWarning", "Storm Warning", "World",
            new double[] { 0, 1 }, 1, true, false),
        new( 59, "HeatMapSensitivity", "Heatmap Sensitivity", "World",
            new double[] { 0, 0.25, 0.5, 1, 1.5, 2 }, 1, false, false),
        new( 66, "DayNightLength", "24 Day Cycle", "World",
            new double[] { 10, 20, 30, 40, 50, 60, 90, 120 }, 60, false, false),
        new( 67, "DayLightLength", "Day Light Length", "World",
            new double[] { 0, 4, 6, 8, 10, 12, 14, 16, 18, 20, 24 }, 18, false, false),
        new( 53, "AirDropMarker", "Mark Air Drops", "World",
            new double[] { 0, 1 }, 1, true, false),
        new( 68, "AllowMap", "Allow Map", "World",
            new double[] { 0, 1 }, 1, true, false),
        new( 69, "AllowCompass", "Allow Compass", "World",
            new double[] { 0, 1 }, 1, true, false),
        new( 70, "AllowScreenMarkers", "Allow Screen Markers", "World",
            new double[] { 0, 1 }, 1, true, false),
        new( 71, "ShowLocationInfo", "Show Location Info", "World",
            new double[] { 0, 1 }, 1, true, false),
        new( 72, "ShowDayTime", "Show Day/Time", "World",
            new double[] { 0, 1 }, 1, true, false),
        new( 77, "LootMaxTier", "Loot Max Tier", "Resources",
            new double[] { 1, 2, 3, 4, 5, 6 }, 6, false, false),
        new( 62, "GlobalLSModifier", "Global LootStage", "Resources",
            new double[] { 0.25, 0.5, 1, 1.5, 2 }, 1, false, false),
        new( 63, "BiomeLSModifier", "Biome LootStage", "Resources",
            new double[] { 0.25, 0.5, 1, 1.5, 2 }, 1, false, false),
        new( 64, "POITierLSModifier", "POI Tier LootStage", "Resources",
            new double[] { 0.25, 0.5, 1, 1.5, 2 }, 1, false, false),
        new( 75, "LootRespawnDays", "Loot Respawn Days", "Resources",
            new double[] { -1, 5, 7, 10, 15, 20, 30, 40, 50 }, 7, false, false),
        new( 76, "LootTimer", "Loot Time", "Resources",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3 }, 1, false, false),
        new( 90, "LootBagChance", "Loot Bag Chance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 78, "GlobalLootCount", "Global Loot Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 79, "FoodLootCount", "Food Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 80, "DrinkLootCount", "Drink Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 81, "MedicalLootCount", "Medical Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 82, "AmmoLootCount", "Ammo Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 83, "ResourceLootCount", "Resource Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 84, "ArmorLootCount", "Armor Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 85, "MeleeLootCount", "Melee Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 86, "RangedLootCount", "Ranged Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 87, "DukesLootCount", "Dukes Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 88, "CraftingMagazinesLootCount", "Magazines Abundance", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 89, "TreasureMapChance", "Treasure Map Chance", "Resources",
            new double[] { 0, 0.25, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2, 3 }, 1, false, false),
        new(101, "MiningOutput", "Mining Output", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 91, "CropOutput", "Crop Output", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 92, "SeedDropOutput", "Seed Drop Output", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new(102, "HarvestingOutput", "Harvesting Output", "Resources",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 3, 4, 5 }, 1, false, false),
        new( 93, "CropGrowthSpeed", "Crop Growth", "Resources",
            new double[] { 1000, 0, 0.2, 0.5, 0.75, 1, 1.5, 2, 3 }, 1, false, true),
        new( 96, "CraftingProgression", "Crafting Progression", "Crafting",
            new double[] { 0, 1 }, 1, true, false),
        new(100, "CraftingMaxTier", "Crafting Max Tier", "Crafting",
            new double[] { 1, 2, 3, 4, 5, 6 }, 6, false, false),
        new(115, "PointsPerMagazine", "Magazine Points", "Crafting",
            new double[] { 0, 1, 2, 3, 4, 5, 6, 7 }, 1, false, false),
        new( 94, "BackpackCrafting", "Backpack Crafting", "Crafting",
            new double[] { 0, 1, 2, 3 }, 1, false, false),
        new( 95, "WorkstationCrafting", "Workstation Crafting", "Crafting",
            new double[] { 0, 1 }, 1, true, false),
        new(104, "SmeltingType", "Smelter Type", "Crafting",
            new double[] { 0, 1 }, 0, true, false),
        new( 97, "CraftingTime", "Crafting Time", "Crafting",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3 }, 1, false, false),
        new( 98, "CraftingInput", "Crafting Input", "Crafting",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3 }, 1, false, false),
        new( 99, "CraftingOutput", "Crafting Output", "Crafting",
            new double[] { 0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3 }, 1, false, false),
        new(103, "ScrappingOutput", "Scrapping Output", "Crafting",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3 }, 1, false, false),
        new(105, "DewCollectorTime", "Dew Collector Time", "Crafting",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3 }, 1, false, false),
        new(106, "DewCollectorOutput", "Dew Collector Yield", "Crafting",
            new double[] { 1, 2, 3, 4, 5 }, 1, false, true),
        new(107, "DewCollectorInput", "Dew Collector Input", "Crafting",
            new double[] { 0, 1, 2, 3 }, 1, false, true),
        new(108, "ApiaryTime", "Apiary Time", "Crafting",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3 }, 1, false, false),
        new(109, "ApiaryOutput", "Apiary Output", "Crafting",
            new double[] { 1, 2, 3, 4, 5 }, 1, false, true),
        new(110, "ApiaryInput", "Apiary Input", "Crafting",
            new double[] { 0, 0.2, 0.4, 0.6, 0.8, 1, 1.5, 2, 3 }, 1, false, false),
        new( 21, "ItemDegradation", "Item Degradation", "Crafting",
            new double[] { 0, 0.25, 0.5, 1, 1.5, 2 }, 1, false, false),
        new(113, "RepairTypes", "Item Repair Types", "Crafting",
            new double[] { 0, 1, 2, 3 }, 3, false, false),
        new(114, "MaxDegradationAmount", "Max Degrade Amount", "Crafting",
            new double[] { 0, 0.05, 0.1, 0.15, 0.2, 0.25 }, 0, false, false),
        new(128, "TradersEnabled", "Trading Enabled", "Traders",
            new double[] { 0, 1 }, 1, true, false),
        new(129, "VendingEnabled", "Vending Machines Enabled", "Traders",
            new double[] { 0, 1 }, 1, true, false),
        new(127, "TraderHours", "Trader Hours", "Traders",
            new double[] { 0, 1, 2, 3, 4, 5, 6 }, 0, false, false),
        new(132, "TraderProtection", "Trader Protection", "Traders",
            new double[] { 0, 1, 2 }, 0, false, false),
        new(126, "TraderDialog", "Trading Dialog", "Traders",
            new double[] { 0, 1 }, 1, true, false),
        new( 65, "GlobalTSModifier", "Global TraderStage", "Traders",
            new double[] { 0.25, 0.5, 1, 1.5, 2 }, 1, false, false),
        new(136, "TraderMaxTier", "Trader Max Tier", "Traders",
            new double[] { 1, 2, 3, 4, 5, 6 }, 6, false, false),
        new(134, "TraderItemAbundance", "Trader Item Abundance", "Traders",
            new double[] { 0.25, 0.5, 1, 1.5, 2 }, 1, false, false),
        new(138, "VendingItemAbundance", "Vending Item Abundance", "Traders",
            new double[] { 0.25, 0.5, 1, 1.5, 2 }, 1, false, false),
        new(133, "TraderResetInterval", "Trader Reset Interval", "Traders",
            new double[] { -1, 1, 2, 3, 4, 5, 6, 7, 14 }, -1, false, false),
        new(137, "VendingResetInterval", "Vending Reset Interval", "Traders",
            new double[] { -1, 1, 2, 3, 4, 5, 6, 7, 14 }, -1, false, false),
        new(130, "TraderSellPrices", "Traders Sell Price", "Traders",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 3, 4 }, 1, false, false),
        new(131, "TraderBuyPrices", "Traders Buy Price", "Traders",
            new double[] { 0, 0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2, 3, 4 }, 1, false, false),
        new(135, "TraderBuyLimit", "Trader Buy Limit", "Traders",
            new double[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }, 3, false, false),
        new(139, "ChallengesEnabled", "Challenges Enabled", "Tasks",
            new double[] { 0, 1 }, 1, true, false),
        new(118, "QuestsEnabled", "Quests Enabled", "Tasks",
            new double[] { 0, 1 }, 1, true, false),
        new(140, "IntroChallengesEnabled", "Intro Challenges Enabled", "Tasks",
            new double[] { 0, 1 }, 1, true, false),
        new(119, "IntroQuestEnabled", "Intro Quest Enabled", "Tasks",
            new double[] { 0, 1 }, 1, true, false),
        new(120, "TraderToTraderQuestsEnabled", "Trader to Trader Quests", "Tasks",
            new double[] { 0, 1 }, 1, true, false),
        new(124, "BuriedQuestsEnabled", "Buried Quests Enabled", "Tasks",
            new double[] { 0, 1 }, 1, true, false),
        new(125, "POIQuestsEnabled", "POI Quests Enabled", "Tasks",
            new double[] { 0, 1 }, 1, true, false),
        new(122, "QuestsPerTier", "Quests per Tier", "Tasks",
            new double[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 }, 10, false, false),
        new(123, "QuestProgressionDailyLimit", "Quests per Day", "Tasks",
            new double[] { -1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }, 4, false, false),
        new(121, "StarterSkillPoints", "Starter Skill Points", "Tasks",
            new double[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }, 4, false, false),
        new(141, "VehicleFuelUsage", "Vehicle Fuel Usage", "Misc",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new(142, "VehicleEntityDamage", "Vehicle Entity Damage", "Misc",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new(143, "VehicleBlockDamage", "Vehicle Block Damage", "Misc",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new(144, "VehicleSelfDamage", "Vehicle Self Damage", "Misc",
            new double[] { 0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1, 1.25, 1.5, 2, 2.5, 3 }, 1, false, false),
        new(145, "ElectricalOutput", "Electrical Output", "Misc",
            new double[] { 0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 3 }, 1, false, false),
        new(146, "SillyCelebrate", "Celebrate Kills", "Misc",
            new double[] { 0, 1, 2 }, 0, false, false),
        new(147, "SillyBigHeads", "Big Heads", "Misc",
            new double[] { 0, 1 }, 0, true, false),
        new(148, "SillyTinyZombies", "Tiny Zombies", "Misc",
            new double[] { 0, 1 }, 0, true, false),
        new(150, "SillyLowGravity", "Gravity", "Misc",
            new double[] { 0.5, 0.6, 0.7, 0.8, 0.9, 1 }, 1, false, false),
        new(149, "SillySounds", "Silly Sounds", "Misc",
            new double[] { 0, 1 }, 0, true, false),
        new(151, "SillyBlackandWhite", "Black and White", "Misc",
            new double[] { 0, 1 }, 0, true, false),
    };

    private static readonly Dictionary<int, SandboxOption> _byId =
        All.ToDictionary(o => o.Id);

    private static readonly Dictionary<string, SandboxOption> _byName =
        All.ToDictionary(o => o.Name, StringComparer.OrdinalIgnoreCase);

    public static SandboxOption? ById(int id) => _byId.GetValueOrDefault(id);
    public static SandboxOption? ByName(string name) => _byName.GetValueOrDefault(name);

    /// <summary>Position of an option in the emit order. Used to sort blocks when encoding.</summary>
    public static int UiIndex(int id)
    {
        for (var i = 0; i < All.Count; i++)
            if (All[i].Id == id) return i;
        return int.MaxValue;
    }

    /// <summary>The stock presets, with the exact codes the game ships.</summary>
    public static readonly IReadOnlyList<SandboxPreset> Presets = new SandboxPreset[]
    {
        // Rank is the game's own difficulty scale (2..7), in ascending order of difficulty.
        new("Scavenger",        "AAAKABKACKADKARDBNB", true, 2),
        new("Adventurer",       "AAAJABJACJADJARFBNC", true, 3),
        new("Nomad",            "",                    true, 4),   // all defaults — the 1x baseline
        new("Warrior",          "AAAGABGACGADGARJBND", true, 5),
        new("True Survivalist", "AAAEABEACEADEARKBNE", true, 6),
        new("Insane",           "AAADABDACDADDARLBNF", true, 7),
        new("Almost Creative", "ABEABTBBWADFN", false),
        new("Chibi Mode", "AAAJABJACJADJAEIARFAGIAHJAFJAIEAKEAJDASGENDBAAAYBAZBBBABDCAUBAMJBUEBSEBTEAQBBIBBKEBLEBMBBNCCVHBZDCACCLDCMDCXBCYCDMJDAIDXIDNIDOIDYIDPGDTGEBGEEGAVCEXFCNDETFFLGFMJFOGFQCFRBFSBFUB", false),
        new("Dumpster Diver", "AAUABUCCVLCABCXBDMKDALDFJDKDDXADNADOADYBEABDVGDZFEXFFKA", false),
        new("Legacy Survival", "AAHIAJDBACAPAAUAAMLBREBUEBSCBNCBPABOABVACDACVGCGACBACXBDDGDJIDNJDOJDSAELAEABEBGCNDFEDFIDFAFEOAFKAEPAEQA", false),
        new("Disaster Film", "AAXBAYDAZFBDFBVACFHDAKDDJDKFAVFEKFFOJ", false),
        new("Caveman Life", "AAADABJBTFCDACWBCAACQACRADNADOADWAEZAEWAFGAFKAFPA", false),
        new("Dying World", "AAMABTBCAACXADMADOAEBAEJAFEAFIAFDIFHIFJAEOAEPA", false),
        new("Undead Matinee", "AAAFABIACGADGAEIARJAGHAHEAFIAKEAJCBACAWBAXBAYDAZDBDGAPAAMFBUEBSEBFKBQEAQCBJABKABLBBMBBNCBPJCIDCJDCVEBZFCAGCFECYDDBDDCDDDDDEBDGDDHJDIBDKFAVEEKDFDFFHF", false),
        new("Seven days Later", "AAAGABGACGADGARJBACAWFAXBAYDAPABUEBSEBICBJCBKCBLCBMCBPFBZFBYC", false),
        new("Madmoles Mayhem", "AAAGABGACGAPAAMIAWBAXCAZEBACBFIBGIBHIBIBBKEBLEBNFBUEBSECIDCJDBZFCVDDCDDDDDEDDFDDGDDJFEXF", false),
        new("Bite Club", "AAAGABGACGADGARJAHJBADBDGBIBBMCBNEBPFBZFCFDCXADADEYA", false),
    };
}

/// <param name="Code">The exact code string the game ships for this preset. Empty = all defaults.</param>
/// <param name="IsDifficulty">True for the six difficulty levels (Scavenger…Insane).</param>
/// <param name="Rank">
/// The game's own difficulty rank, 2 (Scavenger) … 7 (Insane); 0 for theme presets.
/// Taken from the game data rather than inferred from list order, so it stays right if the
/// presets are ever reordered. It tracks the damage curve exactly — Scavenger deals 2x and
/// takes 0.5x; Insane deals 0.5x and takes 2.5x; Nomad is the 1x/1x baseline.
/// </param>
public sealed record SandboxPreset(string Name, string Code, bool IsDifficulty, int Rank = 0)
{
    private const int MinRank = 2, MaxRank = 7;

    /// <summary>Difficulty as 0 (easiest) … 1 (hardest). Used to ramp the button colour.</summary>
    public double Severity =>
        Rank <= 0 ? 0 : Math.Clamp((Rank - MinRank) / (double)(MaxRank - MinRank), 0, 1);
}
